add: License header in the top of the files in the smswithoutborders_libsig directory.
smswithoutborders/lib_signal_double_ratchet_python pull request #16
Opened 2024-09-25 12:28 UTC by wuX4an

Response of [this issue.](https://github.com/smswithoutborders/lib_signal_double_ratchet_python/issues/15)

2024-09-25 12:46 UTC, PromiseFru requested changes
Thank you, @wuX4an! Just a few more tweaks are needed. 😉

2024-09-25 12:46 UTC, PromiseFru commented on smswithoutborders_libsig/helpers.py
> +"""
Keep a single empty line after the top file docstring.

2024-09-25 12:46 UTC, PromiseFru commented on smswithoutborders_libsig/keystore.py
> +# A module for managing a secure keystore.
Keep the existing file description at the top of the docstring.

```suggestion
"""
A module for managing a secure keystore.
 
This program is free software: you can redistribute it under the terms
of the GNU General Public License, v. 3.0. If a copy of the GNU General
Public License was not distributed with this file, see <https://www.gnu.org/licenses/>.
"""

```

2024-09-25 12:46 UTC, PromiseFru commented on smswithoutborders_libsig/ratchets.py
> +# A module that implements the ratchet mechanism
Keep the existing file description at the top of the docstring.

2024-09-25 13:21 UTC, wuX4an commented
> > Response of [this issue.](https://github.com/smswithoutborders/lib_signal_double_ratchet_python/issues/15)
> 
> Tip
> 
> To link your pull request (PR) to the relevant issue and ensure that the issue is automatically closed once the PR is merged, you can use GitHub's supported keywords in the PR title.
> 
> For example, you can use keywords like "fixes," "closes," or "resolves" followed by the issue number. Here’s a format you can follow:
> 
> ```
> Fixes #123
> ```
> 
> This will automatically close issue `#123` when the PR is merged.
> 
> For more information on this, you can check the [GitHub documentation](https://docs.github.com/en/issues/tracking-your-work-with-issues/using-issues/linking-a-pull-request-to-an-issue).

# Thanks for the tip.
I'm learning to contribute to projects and I'm only limited to markdowns and troubleshooting dependency errors in python.

2024-09-26 08:44 UTC, PromiseFru commented
@wuX4an, please resolve the rest of the requested changes so I can merge the PR. 🙂

2024-09-27 22:27 UTC, wuX4an commented
@PromiseFru I already did it, sorry, I didn't know xd.

2024-09-28 13:09 UTC, PromiseFru commented
> @PromiseFru I already did it, sorry, I didn't know xd.

Hey @wuX4an, you marked the requests resolved without making the necessary file changes.
Please review the comments and update the files, ratchets.py and helpers.py, before marking the conversation as resolved. :)

https://github.com/smswithoutborders/lib_signal_double_ratchet_python/pull/16#discussion_r1775149792
https://github.com/smswithoutborders/lib_signal_double_ratchet_python/pull/16#discussion_r1775160032

2024-09-28 15:11 UTC, wuX4an commented
> > @PromiseFru I already did it, sorry, I didn't know xd.
> 
> Hey @wuX4an, you marked the requests resolved without making the necessary file changes. Please review the comments and update the files, ratchets.py and helpers.py, before marking the conversation as resolved. :)
> 
> [#16 (comment)](https://github.com/smswithoutborders/lib_signal_double_ratchet_python/pull/16#discussion_r1775149792) [#16 (comment)](https://github.com/smswithoutborders/lib_signal_double_ratchet_python/pull/16#discussion_r1775160032)


Oh, F***k. I didn't realize xd

2024-09-28 16:02 UTC, PromiseFru requested changes

2024-09-28 16:02 UTC, PromiseFru commented on smswithoutborders_libsig/ratchets.py
> +A module for managing a secure keystore.
```suggestion
A module that implements the ratchet mechanism.
```

2024-09-28 17:40 UTC, PromiseFru approved these changes
Thank you, @wuX4an!

2024-09-28 17:41 UTC, merged